spring:
  application:
    name: springsecurity
  security:
    user:
      name: aca
      password: aca

#  datasource:
#    url: jdbc:h2:mem:mydb
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

# application.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/aca
    username: aca
    password: aca
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true



