spring:
  application:
    name: springsecurity

  datasource:
    url: jdbc:postgresql://localhost:5432/aca
    username: aca
    password: aca
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true



